<div id="about">
    <div class="container">
        <div class="section">
            <h1>Welcome</h1>
            <div class="row">
                <div class="col-sm-8">
                    <p class="lead">Situated in the hills just north of Faro, Casa Alfarroba is located in the rolling
                        country
                        side within a series of homes and farms known as Azinhal e Amendoira.</p>
                    <p>Casa Alfarroba is set less then 1km from the village of Machados, placing it equidistant between
                        the towns
                        of Estoi and Sao Bras de Alportel and just about 17 km from the airport. With the nearest
                        motorway just under
                        6km away from the villa, Casa Alfraroba has easy access to the entire Algarve region. For those
                        who wish to
                        travel further the Spanish border is less than an hour away as is the western town of Lagos.</p>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
</div>
