<a class="anchor" id="amenities"></a>
<div class="amenities">
    <div class="container">
        <div class="section">
            <h1 data-aos="fade-in">Amenities</h1>
            <div class="row text-center">
                <div class="col-sm-4" data-aos="fade-up">
                    <img src="assets/images/swimming.png" class="image" alt="Infinity Pool">
                    <h2>Infinity Pool</h2>
                    <p>10 x 5 metre pool bordered by a substantial sun terrace with views of the surrounding valley.</p>
                </div>
                <div class="col-sm-4" data-aos="fade-up" data-aos-delay="50">
                    <img src="assets/images/bedrooms.png" class="image" alt="4 Bedrooms">
                    <h2>4 Bedrooms</h2>
                    <p>3 en-suite with a further family bathroom. The villa has two double bedrooms upstairs with two
                        twin-bedded rooms on the ground floor. </p>
                </div>
                <div class="col-sm-4" data-aos="fade-up" data-aos-delay="100">
                    <img src="assets/images/chess.png" class="image" alt="Garden Chess">
                    <h2>Garden chess set</h2>
                    <p>3,500 square metre formal garden area protected by walls, fencing, and electronic gates with plenty
                        of areas to walk and sit in.</p>
                </div>
            </div>
            <br><br>
            <div class="row text-center">
                <div class="col-sm-4" data-aos="fade-up">
                    <img src="assets/images/aircon.png" class="image" alt="Air Conditioning">
                    <h2>Air conditioning</h2>
                    <p>Individually controlled air conditioning units throughout the villa help maintain comfort.</p>
                </div>
                <div class="col-sm-4" data-aos="fade-up" data-aos-delay="50">
                    <img src="assets/images/tennis.png" class="image" alt="Tennis Court">
                    <h2>Tennis court</h2>
                    <p>For those with an abundance of energy the villa allows visitors to thrash it out on the court
                        situated just outside the formal garden.</p>
                </div>
                <div class="col-sm-4" data-aos="fade-up" data-aos-delay="100">
                    <img src="assets/images/bbq.png" class="image" alt="BBQ">
                    <h2>BBQ</h2>
                    <p>The aromas that drift from its chimney summon people to share a meal around the table on the
                        veranda.</p>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
</div>
