<a class="anchor" id="contact"></a>
<div class="contact">
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-3 white">
                    <h1>Contact</h1>
                    <p><i class="fas fa-user"></i>David Patterson</p>
                    <p><i class="fas fa-phone"></i>+ 44 (0)1494 722648</p>
                    <p><i class="fas fa-envelope"></i>d.patterson@talk21.com</p>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
</div>
