<div id="contact">
    <div class="section">
        <div class="container">
            <h1>Contact</h1>
            <div class="row">
                <div class="col-md-8">

                </div>
                <div class="col-md-4">
                    <p><i class="fas fa-user"></i>David Patterson</p>
                    <p><i class="fas fa-phone"></i>+ 44 (0)1494 722648</p>
                    <p><i class="fas fa-envelope"></i>d.patterson@talk21.com</p>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
</div>
