<div id="gallery" >
    <div class="container">
        <h2>Gallery</h2>
        <div class="row">
            <div class="clearfix"></div>
            <div class="templatemo-gallery-category" style="font-size:16px; margin-top:80px;">
                <div class="text-center">
                    <a class="active" href=".gallery">All</a> / <a href=".gallery-design">Web Design </a>/ <a href=".gallery-graphic">Graphic</a> / <a href=".gallery-inspiration">Inspiration</a> / <a href=".gallery-creative">Creative</a>
                </div>
            </div>
        </div> <!-- /.row -->


        <div class="clearfix"></div>
        <div class="text-center">
            <ul class="templatemo-project-gallery" >
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-graphic" >
                    <a class="colorbox" href="images/full-gallery-image-1.jpg" data-group="gallery-graphic">
                        <div class="templatemo-project-box">

                            <img src="images/gallery-image-1.jpg" class="img-responsive" alt="gallery" />

                            <div class="project-overlay">
                                <h5>Graphic</h5>
                                <hr />
                                <h4>TEA POT</h4>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-creative" >
                    <a class="colorbox" href="images/full-gallery-image-2.jpg" data-group="gallery-creative">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-2.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Creative</h5>
                                <hr />
                                <h4>BREAKFAST</h4>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-inspiration" >
                    <a class="colorbox" href="images/full-gallery-image-3.jpg" data-group="gallery-inspiration">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-3.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Inspiration</h5>
                                <hr />
                                <h4>GREEN COLORS</h4>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-design" >
                    <a class="colorbox" href="images/full-gallery-image-4.jpg" data-group="gallery-design">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-4.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Web Design</h5>
                                <hr />
                                <h4>CAMERA</h4>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-inspiration" >
                    <a class="colorbox" href="images/full-gallery-image-5.jpg" data-group="gallery-inspiration">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-5.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Inspiration</h5>
                                <hr />
                                <h4>PLANT</h4>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2  gallery gallery-inspiration" >
                    <a class="colorbox" href="images/full-gallery-image-6.jpg" data-group="gallery-inspiration">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-6.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Inspiration</h5>
                                <hr />
                                <h4>CABLE TRAIN</h4>
                            </div>
                        </div>
                    </a>
                </li>

                <li class="col-lg-2 col-md-2 col-sm-2 gallery gallery-design" >
                    <a class="colorbox" href="images/full-gallery-image-7.jpg" data-group="gallery-design">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-7.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Web Design</h5>
                                <hr />
                                <h4>CITY</h4>
                            </div>
                        </div>
                    </a>
                </li>

                <li class="col-lg-2 col-md-2 col-sm-2 gallery gallery-creative" >
                    <a class="colorbox" href="images/full-gallery-image-8.jpg" data-group="gallery-creative">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-8.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Creative</h5>
                                <hr />
                                <h4>BIRDS</h4>
                            </div>
                        </div>
                    </a>
                </li>

                <li class="col-lg-2 col-md-2 col-sm-2 gallery gallery-graphic" >
                    <a class="colorbox" href="images/full-gallery-image-9.jpg" data-group="gallery-graphic">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-9.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Graphic</h5>
                                <hr />
                                <h4>NATURE</h4>
                            </div>
                        </div>
                    </a>
                </li>

                <li class="col-lg-2 col-md-2 col-sm-2 gallery gallery-inspiration" >
                    <a class="colorbox" href="images/full-gallery-image-10.jpg" data-group="gallery-inspiration">
                        <div class="templatemo-project-box">
                            <img src="images/gallery-image-10.jpg" class="img-responsive" alt="gallery" />
                            <div class="project-overlay">
                                <h5>Inspiration</h5>
                                <hr />
                                <h4>DOGGY</h4>
                            </div>
                        </div>
                    </a>
                </li>

            </ul><!-- /.gallery -->
        </div>
        <div class="clearfix"></div>
        <div class="row text-center">
            <a class="btn_loadmore btn btn-lg btn-orange" href="#" role="button">LOAD MORE</a>
        </div>
    </div><!-- /.container -->
</div> <!-- /.templatemo-portfolio -->