<div id="gallery">
    <div class="container">
        <div class="row">
            <div class="section">
                <h1>Gallery</h1>

                <div class="tz-gallery">
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/exterior_1.jpg">
                                <img src="./assets/gallery/exterior_1.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/villa_1.jpg">
                                <img src="./assets/gallery/villa_1.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_1.jpg">
                                <img src="./assets/gallery/garden_1.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_2.jpg">
                                <img src="./assets/gallery/garden_2.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_3.jpg">
                                <img src="./assets/gallery/garden_3.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_4.jpg">
                                <img src="./assets/gallery/garden_4.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_5.jpg">
                                <img src="./assets/gallery/garden_5.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/garden_6.jpg">
                                <img src="./assets/gallery/garden_6.jpg" alt="Park">
                            </a>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                                <img src="./assets/gallery/exterior_2.jpg" alt="Park">
                            </a>
                        </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/pool.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/interior_1.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/interior_2.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/interior_3.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/interior_4.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/villa_2.jpg" alt="Park">
                        </a>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                            <img src="./assets/gallery/villa_3.jpg" alt="Park">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
