<a class="anchor" id="gallery"></a>
<div class="container">

        <div class="section">
            <h1 data-aos="fade-in">Gallery</h1>
            <div class="tz-gallery" data-aos="fade-in">
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/exterior_1.jpg">
                        <img src="./assets/gallery/exterior_1.jpg" alt="Gate to villa">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/villa_1.jpg">
                        <img src="./assets/gallery/villa_1.jpg" alt="Villa from drive">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/garden_5.jpg">
                        <img src="./assets/gallery/garden_5.jpg" alt="Giant chess board">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/garden_2.jpg">
                        <img src="./assets/gallery/garden_2.jpg" alt="Garden stairs">
                    </a>
                </div>
                <div class="col-sm-12 col-md-4">
                    <a class="lightbox" href="./assets/gallery/garden_1.jpg">
                        <img src="./assets/gallery/garden_1.jpg" alt="Garden view">
                    </a>
                </div>
                <!--                        <div class="col-sm-6 col-md-4">-->
                <!--                            <a class="lightbox" href="./assets/gallery/garden_3.jpg">-->
                <!--                                <img src="./assets/gallery/garden_3.jpg" alt="Park">-->
                <!--                            </a>-->
                <!--                        </div>-->
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/garden_4.jpg">
                        <img src="./assets/gallery/garden_4.jpg" alt="Drive up to villa">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/villa_2.jpg">
                        <img src="./assets/gallery/villa_2.jpg" alt="Villa from above">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/interior_1.jpg">
                        <img src="./assets/gallery/interior_1.jpg" alt="Dining area">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/interior_2.jpg">
                        <img src="./assets/gallery/interior_2.jpg" alt="Lounge">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/interior_3.jpg">
                        <img src="./assets/gallery/interior_3.jpg" alt="Master bedroom">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/interior_4.jpg">
                        <img src="./assets/gallery/interior_4.jpg" alt="Bedroom with twin beds">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/garden_6.jpg">
                        <img src="./assets/gallery/garden_6.jpg" alt="View from 1st floor of villa">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/pool.jpg">
                        <img src="./assets/gallery/pool.jpg" alt="Pool from villa">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/villa_3.jpg">
                        <img src="./assets/gallery/villa_3.jpg" alt="Villa from the pool">
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="lightbox" href="./assets/gallery/exterior_2.jpg">
                        <img src="./assets/gallery/exterior_2.jpg" alt="Private tennis court">
                    </a>
                </div>
            </div>
        </div>

</div>

