<a class="anchor" id="leisure"></a>
<div class="leisure">
    <div class="section">
        <div class="container">
            <h1>Leisure</h1>
            <div class="wrapper">
                <div class="card">
                    <div class="thumbnail">
                        <img src="assets/images/attractions.jpg" alt="Attractions">
                        <div class="content">
                            <h3 class="text-center">Attractions</h3>
                            <p>Markets, waterparks, ruins, shopping, site seeing. Just a few of the things that will
                                capture your heart and imagination in the Algarve.</p>
                        </div>
                    </div>
                    <button class="btn">View more</button>
                </div>
                <div class="card">
                    <div class="thumbnail">
                        <img src="assets/images/beach.jpg" alt="Beaches">
                        <div class="content">
                            <h3 class="text-center">Beaches</h3>
                            <p>From Barril to Trafal enjoy a dip in the Atlantic, relax in the sun, or build sand
                                castles with the family. </p>
                        </div>
                    </div>
                    <button class="btn">View more</button>
                </div>
                <div class="card">
                    <div class="thumbnail">
                        <img src="assets/images/dining.jpg" alt="Dining">
                        <div class="content">
                            <h3 class="text-center">Dining</h3>
                            <p>Resturants nestled in neighboring towns and situated in the country side. We have some
                                our our favourites we would love to share with you.</p>
                        </div>
                    </div>
                    <button class="btn">View more</button>
                </div>
                <div class="card">
                    <div class="thumbnail">
                        <img src="assets/images/golf.jpg" alt="Golf">
                        <div class="content">
                            <h3 class="text-center">Golf</h3>
                            <p>Spend a theraputic day hitting the links on one of the lush green courses not far from
                                Casa Alfarroba.</p>
                        </div>
                    </div>
                    <button class="btn">View more</button>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
</div>
